export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECTS = "ADD_PROJECTS";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const ERROR_PROJECT = "ERROR_PROJECT";

export const HOMEWORKS_PROJECT = "HOMEWORKS_PROJECT";
export const ADD_HOMEWORK = "ADD_HOMEWORK";
export const VALIDATE_HOMEWORK = "VALIDATE_HOMEWORK";
export const DELETE_HOMEWORK = "DELETE_HOMEWORK";
export const CURRENT_HOMEWORK = "CURRENT_HOMEWORK";
export const UPDATE_HOMEWORK = "UPDATE_HOMEWORK";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDDEN_ALERT = "HIDDEN_ALERT";

export const SUCCESS_REGISTER = "SUCCESS_REGISTER";
export const ERROR_REGISTER = "ERROR_REGISTER";
export const GET_USER = "GET_USER";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const CLOSE_SESION = "CLOSE_SESION";
